### PR TITLE
Laravel 9

### PR DESCRIPTION
**Pull request by edgrosvenor**
Happy Laravel release day, Ryan!

### CODE REVIEW

**Comment by ryangjchandler** [comment]
@edgrosvenor Do you fancy updating the workflow file to include Laravel 9?

**Comment by edgrosvenor** [comment]
@ryangjchandler Happy to. Will it run for me? It didn't before because I'm a first time contributor.

**Comment by ryangjchandler** [comment]
@edgrosvenor It will now yeah

**Comment by ryangjchandler** [comment]
Lol, maybe it won't!

**Comment by ryangjchandler** [comment]
@edgrosvenor Looks like package-tools need to be `^1.11`

**Comment by edgrosvenor** [comment]
@ryangjchandler I enabled GitHub Actions on my fork and for some reason only the linting workflow is actually running. So I can't verify that the testing workflow is good.

**Comment by ryangjchandler** [comment]
@edgrosvenor I've fixed the version constraints & added a very simple test while I was at it. Thanks for getting this opened though!

**Comment by edgrosvenor** [comment]
Thanks. I got hung up on the GitHub Actions thing. It's a very recent addition to my own workflow and sometimes it still trips me up. 

Was a pleasure working with you as always!

**Comment by ryangjchandler** [comment]
@edgrosvenor Ping me if you need any Actions assistance. Always up for helping out :)

**Comment by ryangjchandler** [comment]
@edgrosvenor `v1.0.0` is now tagged - only supports Laravel 9. Who wants to use Laravel 8 anyways ;)

**Pull request merged**
